### ISSUE TITLE
Program get's stuck on loading

### ISSUE THREAD

**Issue by svenosman** [AlexanderSharykin/CardIdleRemastered#1]
I downloaded the .zip file, extracted it and double-clicked CardIdleMaster in the Install folder. The program starts loading, but it crashes Windows Explorer. It does create 3 processes and works in Avast Sandbox (crashes in sandbox when I want to start idlling.

**Comment by AlexanderSharykin** [comment]
svenosman,  thank you for the feedback

Card Idle uses an integrated WebBrowser control to display Steam login page and sets a IE registry key for modern HTML compatibility. Seems that something gone wrong. I have updated logging functionality of Card Idle. Please, try again and if the issue still occurs attach log file here. It is also possible that IE wrote something into Windows Event Log - check if there is any info there

Regarding Avast sandbox:

steam-idle.exe process tries to set windows environment variable to fake a real app. i guess Avast denies such attemps. Does IM work in sandbox? I have updated source code, it should show a message if an exception happens. Please, try again and if the issue still occurs post info here

**Comment by svenosman** [comment]
Thank you for replaying to my issue.

In the CardIdleRemastered-master folder I can not find a log file. Nothing has changed on my end. I also can not find the .exe file for IdleMaster to run in Avast Sandbox. Sorry for that.

To be honest, I choose this program because IdleMaster didn't work for me the first time, but now it does. I think I will keep using that program. Thank you for helping me with this issue. I will close this issue.
