### ISSUE TITLE
I can't join steam

### ISSUE THREAD

**Issue by 1003999458** [AlexanderSharykin/CardIdleRemastered#13]
Open the software, select the login button, blank page
![qq 20180416221425](https://user-images.githubusercontent.com/38431629/38814225-93641086-41c3-11e8-9cd1-ee2aa31b0163.png)

**Comment by AlexanderSharykin** [comment]
Sometimes I have the same problem: Internet Explorer doesn't find internet connection. I'm not sure _why_ it happens. In such cases I:
close Login window
launch Internet Explorer and navigate to any web page
when Internet Explorer loads page, click Login in CardIdle again and it show load too

**Comment by fuck-unique-usernames-how-small-minded** [comment]
Any chance of you creating a steam group for CardIdleRemastered - it's very easy.

**Comment by 1003999458** [comment]
thanks ,let me try .

**Comment by AlexanderSharykin** [comment]
At the moment CardIdle has a Steam account: https://steamcommunity.com/profiles/76561198801350858/
and there is IdleMaster group: https://steamcommunity.com/groups/idlemastery, whereCardIdle is a member.

Cardidle users audience is smaller than IdleMaster's. And I don't have time to manage a group 7 days every week. I check CardIdle account and IdleMaster group threads on weekends.

If you have a question, bug report or suggestion, you are welcome to invite Cardidle to friends or create a thread in IdleMaster group. i will answer eventually

**Comment by 1003999458** [comment]
Thanks for your reply, I thought nobody would reply to me.

**Comment by AlexanderSharykin** [comment]
@1003999458 , is your issue resolved?

**Comment by 1003999458** [comment]
Thank you for your second reply. I have added your friends and posted a new group on steam. I look forward to your reply.
