### ISSUE TITLE
Not In Game

### ISSUE THREAD

**Issue by Melidebby** [AlexanderSharykin/CardIdleRemastered#15]
A few days back I used Time Idle and it use to say I was running a # of games (had it at 34).

But now when I use it it only says Not In Game it no longer says how many games I'm running.

**Comment by Melidebby** [comment]
Is there a fix? If I delete Card Idle Remastered then re-extract it should it fix it?

**Comment by AlexanderSharykin** [comment]
fixed in v2.5
