### ISSUE TITLE
mac please!

### ISSUE THREAD

**Issue by Kapleo** [AlexanderSharykin/CardIdleRemastered#17]
idle master python was made for mac but stopped working, and no further ones that were released were for mac. Would love it if this could be made for mac

**Comment by AlexanderSharykin** [comment]
I love it if this could be made for mac, but Card Idle is programmed using WPF framework and it is NOT supported on mac. 
If you donate me a mac os device, I'm willing to learn some native technology and build Card Idle for mac :D
However there is a better chance that some with Python knowledge fix idle master python
