### ISSUE TITLE
the program crashes on start

### ISSUE THREAD

**Issue by mawilek** [AlexanderSharykin/CardIdleRemastered#2]
Hi.
I'm trying your program, but couldn't get it to work. it crashes as soon as I start it. I was able to logon on the first start and it crashed. It doesn't ask me for login since than, just crashing. Wondering, if I can get some help from you. Thanks!
It seems it fails to load my profile, not sure, what can be done.
I'm attaching the error.log
[error.log.txt](https://github.com/AlexanderSharykin/CardIdleRemastered/files/59902/error.log.txt)

**Comment by mawilek** [comment]
seems the problem is my antivirus software (Kaspersky). I could not switch it off, but i tried using a VM with no AV and it seems to work fine.

**Comment by AlexanderSharykin** [comment]
mawilek, thank you for the feedback

i have studied the provided log file and concluded that the reason was a connection failure (it seemed strange because you have logged into your account). but luckily you have fixed it. and now i have updated Card Idle and added a better logging (i admit the log message was not very meaningfull)

**Comment by mawilek** [comment]
I've made you another log in case you are curious, it doesn't really seem to be any better and it still could not get my account name, using my profile ID instead. I'm pretty sure, my antivirus is blocking the connection, but i have no idea, why would it do so. Feel free to ignore this problem, since I can use a VM to idle. But someone else might have a simmilar issue one day.
[error.log.txt](https://github.com/AlexanderSharykin/CardIdleRemastered/files/62710/error.log.txt)

**Comment by AlexanderSharykin** [comment]
Kaspersky antivirus probably doesn't trust Card Idle.
a couple of links which could be helpful:
http://support.kaspersky.com/us/11157#block1
http://support.kaspersky.com/us/kis2015/settings/protection
