### ISSUE TITLE
Login with Win7/IE11

### ISSUE THREAD

**Issue by manstie** [AlexanderSharykin/CardIdleRemastered#20]
The steam login page gets object errors when attempting to log into your profile via card idle. A solution to this is to disable IE11 through Control Panel > Programs > Turn Windows Features on or off.

**Comment by AlexanderSharykin** [comment]
thank you for the report
In v.2.4.3 I added IE 11 compatibility and it solved the problem on my device with Win10+IE 11.
can you please check in "error.log" file (in CardIdle folder) which "IE version" is detected?
do you have such login errors when use older version of Card Idle? e.g. v.2.4, which uses IE 10 compatibility.

**Comment by manstie** [comment]
26/05/2018 1:19:02 PM   IE version 9.11.9600.18665

**Comment by T3rm1** [comment]
Problem is still present with 2.4.3
IE version 9.11.9600.19002

**Comment by AlexanderSharykin** [comment]
I was unable to reproduce the issue with IE 11 in Win7

**Comment by 1nikolas** [comment]
Use awsomium instead of ie. It will fix all the issues
http://web.archive.org/web/20170311012216/http://www.awesomium.com/download

**Comment by AlexanderSharykin** [comment]
In version 2.24.3.14 login page uses Edge engine, Internet Explorer based browser was removed
