### ISSUE TITLE
I get errors when trying to sign in and mobile authentication doesn't show up.

### ISSUE THREAD

**Issue by Lilpuncher** [AlexanderSharykin/CardIdleRemastered#22]
when I press sign in I get the steam page and a script error. when i close the error i get another one. I get like 7 errors then the page refreshes.

**Comment by AlexanderSharykin** [comment]
I need more details to be able to investigate the issue. 

Which CardIdle version and what OS do you use? I cannot repoduce the problem on Win7, Win8 or Win10 with neither IE 11/IE 10, Card Idle v2.4.3/v2.5
What does CardIdle write in "error.log"?
What errors do you see? (a screenshot maybe)
Do you have such erros with other version of CardIdle? please compare v2.4 and v2.5

did you try the suggestion from a similar post?
https://github.com/AlexanderSharykin/CardIdleRemastered/issues/20
"disable IE11 through Control Panel > Programs > Turn Windows Features on or off"

**Comment by Lilpuncher** [comment]
I reopened Cardiff early to take the screenshots but the problem appears to have solved itself.
