### ISSUE TITLE
Auto login

### ISSUE THREAD

**Issue by Gamesiarz** [AlexanderSharykin/CardIdleRemastered#25]
How to enable auto-login on every launch an application? I don't have a checkbox "remember me"

**Comment by AlexanderSharykin** [comment]
CardIdle uses Steam native login page. Login in CardIdle should be identical to login via Internet Explorer. 
I suggest to try to login in IE and if the problem persists, search Steam forums, e.g.
https://steamcommunity.com/discussions/forum/1/1696043806572132808/
