### ISSUE TITLE
Solution to the script error problem

### ISSUE THREAD

**Issue by hoanr** [AlexanderSharykin/CardIdleRemastered#28]
Update your internet explorer to IE 11 [https://support.microsoft.com/en-us/help/17621/internet-explorer-downloads](Link) to fix the issue. Windows 7 comes with IE 8, which, to me, cannot run the script correctly.
Make sure to restart after the update, and then run cardidlemaster.

**Comment by AlexanderSharykin** [comment]
Did Idle Master ever work on that machine? It is targeting IE 10 too. I inherited that code and recently added IE 11. I don't think it is safe to use IE 8 in 2018

Anyway, I updated Card Idle system requirements to clarify that it needs IE 10 or 11.
