### ISSUE TITLE
Can't login.

### ISSUE THREAD

**Issue by MoncholoX** [AlexanderSharykin/CardIdleRemastered#29]
The login window won't redirect back to the program itself, it keeps me logged in in the window and lets me browse as if it was a normal browser tab, with the program staying as "not logged in".
Already tried logging in through internet explorer and click "remember my account", but idlemaster still asks me to log in through its window and giving the same problem.

**Comment by psyco752** [comment]
+1 I have a similar problem, I log in and my steam profile appears in the program and I can navigate as if I were in steam, but I can not grow badges or leave and ask me to log in again.

**Comment by Lock222** [comment]
+1 Same Here.

**Comment by vertigoelectric** [comment]
Looks like this isn't an isolated issue for me.  I look forward to finding out what's going on...

**Comment by Passingby1** [comment]
The problem seems to be caused by Steam:

https://steamcommunity.com/groups/idlemastery/discussions/0/1730955582215529254/

**Comment by Gruvaahl** [comment]
Same here. I logged first time, but now it's what you say

**Comment by AlexanderSharykin** [comment]
Thank you for bringing this to my attention!

Valve changed login/auth a bit: they removed "steamLogin" cookie and it derailed CardIdle login

I will make a fix as soon as possible after I reunit with my development PC.

For now there is a workaround:
 
1. login to your account from CardIdle and when profile page loaded, close the window. 

2. open Settings tab and change any setting. It is necessary to trigger saving and save login data from step 1

3. quit CardIdle
open your Windows user folder, go to AppData folder (it maybe hidden), go to Local folder, go to CardIdleRemastered folder
(full path maybe smth like this: C:\Users\%username%\AppData\Local\CardIdleRemastered)

edit Settings.txt
there should be<SteamLoginSecure> in the following format:  <SteamLoginSecure>**dddddddd**%7C%something</SteamLoginSecure>

the important part is **dddddddd**. it is steam ID

change <SteamProfileUrl> and <SteamLogin>:
<SteamLogin>**dddddddd**</SteamLogin>
<SteamProfileUrl>https://steamcommunity.com/profiles/**dddddddd**</SteamProfileUrl>

and SAVE

4. launch CardIdle again and it should show badges

**Comment by MoncholoX** [comment]
Worked like a charm. Thanks a lot!

**Comment by HyperGrape** [comment]
It did not work for me

**Comment by ledeir** [comment]
Thank you. Worked perfectly for me!
My SteamLogin value had been blank (though my profile was fine)

**Comment by ledeir** [comment]
Thanks. It worked for me.
My SteamLogin value had been blank. My profile was fine though.
I also had to restart steam (just in case it helps HyperGrape)

**Comment by HyperGrape** [comment]
It still doesn't work but Thanks

**Comment by psyco752** [comment]
worked thx for this solution!

**Comment by JKB2K18** [comment]
it still does not work :(

**Comment by AndrewRAN** [comment]
Still doesn't work :(
