### ISSUE TITLE
Cant login when i have family view?

### ISSUE THREAD

**Issue by LilH3ro** [AlexanderSharykin/CardIdleRemastered#3]
Usually after i login on steam i gotta type in the family view key ( i use it as extra security) but when i try and login on this it wont show it and then wont let me login :/

**Comment by AlexanderSharykin** [comment]
thank you for your report
login with family view requires additional step (enter PIN). Personally I never use it and was closing login window too early.
please download v2.3 release

**Comment by LilH3ro** [comment]
Works out great now! thanks for fixing it man!
