### ISSUE TITLE
Errors in login window. 

### ISSUE THREAD

**Issue by jeetsagar** [AlexanderSharykin/CardIdleRemastered#37]
Login window showing script error for 

https://steamcommunity-.akamaihd.net/public/shared/javascript/shared_global.jsv=eI99zHrYoS0F&l=english and 

https://steamcommunity-a.akamaihd.net/public/shared/javascript/shared_responsive_adapter.js?v=qLEcRmcHn-kc&l=english

Also, showing, setTimeZoneCookie undefined for another script.

**Comment by Melidebby** [comment]
yup i'm getting the same its preventing me from logging in

**Comment by Tafoplaka** [comment]
same issue.

**Comment by venimortem** [comment]
I'm getting the same Script Errors, along with _'SetupTooltips' is undefined_ on URL https://steamcommunity.com/login/home/?goto=my/profile

In the error.log, a single login attempt appears like this.

![capture](https://user-images.githubusercontent.com/32726777/46116320-85ab8d80-c1c9-11e8-95a0-c49f98efdd7e.PNG)

I am running on Windows 10 Pro with Internet Explorer 11, however CardIdle appears to be reading my windows version as 6.2 (Windows 8) and IE version 9.11.17134.0. I have tried disabling IE 11 in control panel, and have attempted logging in with CardIdle versions 2.5.4, 2.5.1, 2.4, and 2.3.1, all yielding the same results.

Not really sure what could be causing this, seeing as it's not happening for everyone, but still a decent amount of users. If you need any more information, feel free to ask!

**Comment by ShinyNinetalesTM** [comment]
same here

maybe valve changed something in the login page recently or something?

**Comment by AlexanderSharykin** [comment]
Login to steam account is broken in Internet Explorer. Not the fist time it happens. I expect Valve to make necessary fixes in their site

**Comment by Tafoplaka** [comment]
I think steam has fixed the IE log in issue. I could log in without issues earlier and it idles stuff like normal.

**Comment by ShinyNinetalesTM** [comment]
it is fixed now, yes

**Comment by Johnystar** [comment]
It's still throwing script errors for me...

**Comment by lnfecteDru** [comment]
I resolved this issue by next way:
1. Press Win+R
2. Type regedit
3. Go to HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION
4. Look for CardIdleRemastered.exe
5. Double-click it, change value type to Hexadecimal and change value to 2711
6. Start the program
7. In regedit press F5
8. Login in program
Done.

**Comment by Ralphak** [comment]
Running as an administrator solved it for me.

**Comment by Dark-Nero** [comment]
I have lots of script errors on login attempt: http://prntscr.com/ncxm1g

In registry value of "CardIdleRemastered.exe" was set to 2711 when I checked it.
Running CardIdleRemastered as administrator didn't help.

**Comment by AlexanderSharykin** [comment]
In version 2.24.3.14 login page uses Edge engine, Internet Explorer based browser was removed
