### ISSUE TITLE
errors script on login window 

### ISSUE THREAD

**Issue by MoxieOlv** [AlexanderSharykin/CardIdleRemastered#38]
just me?

**Comment by Jorropo** [comment]
I also have it

**Comment by Jorropo** [comment]
@MoxieOlv I fixed it by lunching idlecard, after it asking me to install a special version of IE, then relunch and it work.

**Comment by Dark-Nero** [comment]
I have lots of script errors on login attempt: http://prntscr.com/ncxm1g

When I launch CardIdleRemastered, I am not offered to install "a special version of IE".

**Comment by AlexanderSharykin** [comment]
In version 2.24.3.14 login page uses Edge engine, Internet Explorer based browser was removed
