### ISSUE TITLE
Not starting up

### ISSUE THREAD

**Issue by Martindroid23** [AlexanderSharykin/CardIdleRemastered#39]
After latest steam update not starting up

**Comment by AlexanderSharykin** [comment]
No repro. CIR is launching for me, and it is also idling (launching "fake" game processes).

CIR is standalone and can work without Steam client - e.g. you don't want to idle, but want to browse showcases. Steam update can have eeffect on idling - it can theoritically make fake processes useless, but I will repeat - it is working for me

If you still have issue, please give more details
