### ISSUE TITLE
Same here

### ISSUE THREAD

**Issue by klyxmaster** [AlexanderSharykin/CardIdleRemastered#41]
here is one of the scripts I get
Line:4432
char: 34
Error: Expected Identifier, string or number
Code: 0
URL: https://steamcommunity-a.akamaihd.net/public/shared/javascript/shared_global.js?v=C3HKtKiIF3cO&l=english

You can ignore it, but then you cannot log in

**Comment by AlexanderSharykin** [comment]
In version 2.24.3.14 login page uses Edge engine, Internet Explorer based browser was removed
