### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by Melidebby** [AlexanderSharykin/CardIdleRemastered#44]
When I click Login I get 4 script errors and I click Yes on all then I put in my username and password and click Sign In but nothing happens.

**Comment by Tafoplaka** [comment]
Same issue. Can no longer log in and also getting the script errors.

**Comment by Melidebby** [comment]
From what I can see it's not been updated since 2018 as well and the steam page has gotten updated a lot since then

Also IE isn't used on Win10 

> 
> 
> Same issue. Can no longer log in and also getting the script errors.

**Comment by Tafoplaka** [comment]
I hope this project is not abandoned. Nearly a week not with no response :(

**Comment by Melidebby** [comment]
Well its last release was Aug 5, 2018 and no response since Nov so.. I'm thinking it was abandoned

**Comment by RENOZIS** [comment]
Had the same issue. How i fixed it:
1. open IE in a background (mb it's not necessary)
2. Try to log in idler app, on all error press Yes.
3. When this page loaded broken press "Forgot password", it will redirect you to the another page that will work fine.
4. From there press "login" on thetop right corner
5. After logging in close the authorisation window

In a couple of secs after that idler should start working

**Comment by AlexanderSharykin** [comment]
In version 2.24.3.14 login page uses Edge engine, Internet Explorer based browser was removed
