### ISSUE TITLE
Add all to queue?

### ISSUE THREAD

**Issue by Kaytiecakes** [AlexanderSharykin/CardIdleRemastered#6]
Sorry if this is a feature and I can't find it, but is there a way to add all the games that have drops remaining in the queue in one press? Or do we have to individually add them to the queue one by one?

I have like 500+ games left to idle and it's driving me bonkers!

Thanks for your hard work!! I love it!

**Comment by AlexanderSharykin** [comment]
Hi
There is such feature
On Badges tab, right under list of games there are buttons:
[Filters]   [^][v][*]   Search []
[^] and [v] add all displayed games from list to Queue
So you can apply some filters and/or search and add only filtered games to Queue

**Comment by Kaytiecakes** [comment]
omg, thank you! 514 games chugging away now :) hahaha
I confused those buttons below as queuing the one I had selected on the list. Oops!
