### ISSUE TITLE
Remove empty space in UI?

### ISSUE THREAD

**Issue by nicholaelaw** [AlexanderSharykin/CardIdleRemastered#7]
Is it possible to remove those big empty area on the left and right of the view port? 

![image](https://user-images.githubusercontent.com/10719482/34428407-6f284b24-ec87-11e7-8e9d-09783a9a8e53.png)

They do not seem to serve any purpose, so removing them should make the UI friendlier.

Oh by the way this remake is fantastic.

**Comment by AlexanderSharykin** [comment]
Hi, @nicholaelaw!
Thanks for compliments, I appreciate your feedback :)

Card idle was designed to have the same look and feel like user Steam profile. That means: user avatar, user name, user level in header, content in central area - and right and left field for Steam background.

I suppose you don't have background set in Steam, so you see only grey area on right and left side. 

CardIdle uses steam background as default, but there is a setting to change it:
 - open "Badges" tab
 - open "Settings"
 - paste some image url into "Background Url" field (for example, I found some cool background on steammarket and copied background url from there. So I have one bg in Steam (which I own) and another in CardIdle (which I don't even have in steam inventory))

please, give this feature a try , and if you still prefer no-background option, I will think about implementing compact mode

**Comment by nicholaelaw** [comment]
Yes I discovered the option after posting the issue. It works fine, I
guess. Maybe set a minimum width so that the background shows when the
window is stretched wide, and hides when the window is narrow? Just some
thought.

2017年12月30日 19:37，"AlexanderSharykin" <notifications@github.com>写道：

**Comment by AlexanderSharykin** [comment]
Hi

After using CardIdle on a device with a small screen, I realised that option to hide the background is necessary.

So I finally implemented it in v2.5, and also made CardIdle to restore previous size then launched

To disable background open "Setting" tab, go to Visual settings and uncheck "Show Background" option

**Comment by nicholaelaw** [comment]
Great work! Much appreciated!

AlexanderSharykin <notifications@github.com>于2018年5月27日 周日16:52写道：
