### ISSUE TITLE
Looping "Periodic Switch" mode

### ISSUE THREAD

**Issue by kostek00** [AlexanderSharykin/CardIdleRemastered#8]
Hello,
Could make so that using periodic switch mode will loop it self? Currently after it reaches end it stops idling. Making it so it will automaticly start from beginning will really help with idling. Or maybe it's like that on every mode?

**Comment by AlexanderSharykin** [comment]
Hello
I'm working on a large settings update, I will include a setting for such looping. Thanks for suggestion
